spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    hikari:
      username: root
      password: root
      # >=6.x com.mysql.cj.jdbc.Driver
      # <=5.x com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        # 指定namespance
        # namespace: cc643c82-9111-48b5-acd5-27868413286f
        # 指定集群名称
        # NJ
        # cluster-name: NJ
        #元数据设置
        metadata:
          instance: c
          haha: hehe
          version: v1
  application:
    name: user
server:
  port: 8080