spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center
    hikari:
      username: show
      password: show123
      # >=6.x com.mysql.cj.jdbc.Driver
      # <=5.x com.mysql.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8010