spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    hikari:
      username: root
      password: root
      # >=6.x com.mysql.cj.jdbc.Driver
      # <=5.x com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        # 指定namespance
        # namespace: cc643c82-9111-48b5-acd5-27868413286f
        # 指定集群名称
        # NJ
        cluster-name: NJ
        #元数据设置
  application:
    name: center
server:
  port: 8010
ribbon:
  eager-load:
    enabled: true #开启饥饿加载
    clients: user #为那个服务开启
